### PR TITLE
Fix example programs, bring the tests back to green

### LINKED ISSUE #4077: Workflow failure: Scheduled Jobs: Upgrade Examples
## Workflow Failure

[Scheduled Jobs: Upgrade Examples](https://github.com/pulumi/pulumi-hugo/blob/master/.github/workflows/scheduled-upgrade-programs.yml) has failed. See the list of failures below:

- [2024-03-21T06:05:30.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8370410444)

- [2024-03-21T18:04:13.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8379660616)

- [2024-03-22T06:05:01.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8386188665)

- [2024-03-23T06:07:06.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8399870889)

- [2024-03-24T06:05:26.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8407304420)

- [2024-03-25T06:06:10.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8415779998)

- [2024-03-26T06:07:32.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8431549230)

- [2024-03-27T06:06:10.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8447373403)

- [2024-03-28T06:07:53.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8463144589)

- [2024-03-29T06:05:09.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8477831855)

- [2024-03-30T06:05:44.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8488812858)

- [2024-03-31T06:05:05.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8496179579)

- [2024-04-01T06:05:47.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8504531432)

- [2024-04-02T06:05:50.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8518165777)

- [2024-04-03T06:05:29.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8533986506)

- [2024-04-04T06:05:25.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8550015027)

- [2024-04-05T06:05:54.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8565729332)

- [2024-04-06T06:05:19.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8579183760)

- [2024-04-07T06:05:25.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8586634727)

- [2024-04-08T06:06:34.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8595316271)

- [2024-04-09T06:05:22.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8611065692)

- [2024-04-10T06:07:14.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8626709672)

- [2024-04-11T06:05:05.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8642240234)

### LINKED ISSUE #4160: Workflow failure: Scheduled Jobs: Run Tests
## Workflow Failure

[Scheduled Jobs: Run Tests](https://github.com/pulumi/pulumi-hugo/blob/master/.github/workflows/scheduled-test.yml) has failed. See the list of failures below:

- [2024-04-10T08:28:28.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8627962123)

- [2024-04-11T08:28:52.000Z](https://github.com/pulumi/pulumi-hugo/actions/runs/8643470860)

### PR DESCRIPTION
**Pull request by cnunciato**
Makes some additional fixes for failures I noticed when running the tests for #4157. 

Should make all the tests 🟢 again. (Also bumps all the Go programs by running `make upgrade-programs`.)

Fixes #4160.
Fixes #4077. (This has also been failing for several weeks.)

### CODE REVIEW

File: themes/default/static/programs/aws-s3bucket-bucketpolicy-java/src/main/java/myproject/App.java [hunk 1]
```diff
@@ -1,26 +1,29 @@
...
-                {
-                  "Version": "2012-10-17",
-                  "Statement": [{
-                    "Effect": "Allow",
-                    "Principal": {"Service": "lambda.amazonaws.com"},
-                    "Action": ["s3:PutObject", "s3:PutObjectAcl"],
-                    "Resource": "%s/*"
-                  }]
-                }""", arn));
+            var policyDocument = bucket.arn().applyValue(arn -> serializeJson(
```
Comment (cnunciato) [inline themes/default/static/programs/aws-s3bucket-bucketpolicy-java/src/main/java/myproject/App.java:14]: This was necessary because Java 11 doesn't support multiline strings specified in this way. We use `serializeJson` elsewhere for this, so I just went with that for consistency.

File: themes/default/static/programs/aws-s3bucket-bucketpolicy-yaml/Pulumi.yaml [hunk 2]
```diff
@@ -11,19 +11,17 @@ resources:
...
-        Statement:
-          - Effect: "Allow"
-            Principal:
-              Service: "lambda.amazonaws.com"
-            Action:
-              - "s3:PutObject"
-              - "s3:PutObjectAcl"
-            Resource:
-              Fn::Sub: "${myBucket.arn}/*"
+        fn::toJSON:
```
Comment (cnunciato) [inline themes/default/static/programs/aws-s3bucket-bucketpolicy-yaml/Pulumi.yaml:14]: This was failing as well on a YAML-related syntax error.

File: themes/default/static/programs/aws-s3bucket-bucketpolicy-yaml/Pulumi.yaml [hunk 3]
```diff
@@ -11,19 +11,17 @@ resources:
...
+                - "s3:PutObject"
+                - "s3:PutObjectAcl"
+              Resource: "${myBucket.arn}/*"
 
 outputs:
-  bucket_name:
-    value: ${myBucket.id}
-  bucket_arn:
-    value: ${myBucket.arn}
+  bucket_name: ${myBucket.id}
```
Comment (cnunciato) [inline themes/default/static/programs/aws-s3bucket-bucketpolicy-yaml/Pulumi.yaml:26]: No need to export `value` wrappers here, so since the other examples don't use it, we can remove it.

**Review by toriancrane — APPROVED** [review]
lgtm
